root: true
parser: babel-eslint
extends:
  - standard
env:
  node: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    globalReturn: false
    modules: false
rules:
  max-len: off
  prefer-rest-params: off
  prefer-destructuring: off
  unicorn/prefer-spread: off
  function-paren-newline: off
  curly:
    - error
  comma-dangle:
    - error
    - always-multiline
  id-length:
    - error
    -
      min: 2
      exceptions:
        - i
        - x
        - y
        - e
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - never
